name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Only run these once since they will be consistent regardless of any node
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Tests
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features \
            -p monero-seed \
            -p polyseed \
            -p monero-wallet-util

      - name: Run Unit Tests Without Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-seed --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package polyseed --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet-util --lib

      - name: Run Unit Tests With Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features --package monero-seed --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features --package polyseed --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --all-features --package monero-wallet-util --lib

      # Doesn't run unit tests with features as the tests workflow will

  integration-tests:
    runs-on: ubuntu-latest
    # Test against all supported protocol versions
    strategy:
      matrix:
        version: [v0.17.3.2, v0.18.3.4]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          monero-version: ${{ matrix.version }}

      - name: Run Integration Tests Without Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet-util --test '*'

      - name: Run Integration Tests
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet-util --all-features --test '*'
